### ISSUE TITLE
Get Agent to verify on Piers' website!

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MsPacManEntry#12]
I received an email from Piers with a stack trace explaining why my agent is unable to perform:

java.lang.ClassNotFoundException: entrants.pacman.Squillyprice01.MyPacMan
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)

This would lead one to believe that there is no class entrants.pacman.Squillyprice01.MyPacMan.

This screenshot of eclipse would say differently, as would the file explorer screenshot:

![screenshot 34](https://user-images.githubusercontent.com/15305479/42098113-907ddf28-7b7f-11e8-9285-8d0a395007e1.png)
![screenshot 33](https://user-images.githubusercontent.com/15305479/42098114-9090b26a-7b7f-11e8-8317-6df88231edfe.png)

I checked spelling as well.

**Comment by Squillyprice01** [comment]
This is DONE!
