### ISSUE TITLE
MM-NEAT and MsPacManEntry have different number of network inputs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MsPacManEntry#14]
At some point, the two projects must have gotten out of sync, which isn't too surprising. In completing #9 I discovered that a network brought over from the current version of MM-NEAT can be loaded correctly (after xml conversion), but that the number of network inputs expected is incorrect, as shown by this error:

```
Constructor: public entrants.pacman.Squillyprice01.edu.southwestern.tasks.mspacman.sensors.mediators.po.POCheckEachDirectionMediator()
Constructor: public entrants.pacman.Squillyprice01.edu.southwestern.tasks.mspacman.data.JunctionNodes()
Constructor: public entrants.pacman.Squillyprice01.edu.southwestern.tasks.mspacman.multitask.po.POProbableGhostStateModeSelector3Mod()
CRASH! inputs = [1.0, 0.03, 0.33, 0.03, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.875, 0.6, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
Exception in thread "Thread-5" java.lang.ArrayIndexOutOfBoundsException: 31
	at entrants.pacman.Squillyprice01.edu.southwestern.networks.TWEANN.process(TWEANN.java:671)
	at entrants.pacman.Squillyprice01.edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNCheckEachDirectionPacManController.getDirectionPreferences(NNCheckEachDirectionPacManController.java:167)
	at entrants.pacman.Squillyprice01.edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNDirectionalPacManController.getDirection(NNDirectionalPacManController.java:33)
	at entrants.pacman.Squillyprice01.edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNPacManController.getAction(NNPacManController.java:131)
	at entrants.pacman.Squillyprice01.MyPacMan.getMove(MyPacMan.java:98)
	at entrants.pacman.Squillyprice01.MyPacMan.getMove(MyPacMan.java:1)
	at pacman.controllers.Controller$1.run(Controller.java:88)
```

We need to sync MsPacManEntry with MM-NEAT, and preferably also come up with some way of quickly/easily verifying that both are in sync. For example, while copying code over from MM-NEAT to this project one file at a time, we should put comments at the top of both the source and target files indicating the timestamp for the copy, so that we can easily check compatibility in the future.

**Comment by schrum2** [comment]
You can test/troubleshoot this with either http://www.cs.utexas.edu/~schrum2/temp/POExperimentsPacMan/bestPacMan.xml
or 
http://www.cs.utexas.edu/~schrum2/temp/POExperimentsPacMan/gen200_bestIn0.xml

These are both 3M Multitask networks evolved with CO Ghosts, so it would not be appropriate to include either of these as the final champion for #15 , but you should be able to use them to make sure the code in this project is compatible with MM-NEAT

**Comment by schrum2** [comment]
The number of inputs was fixed a while ago, but there are still problems with network behavior
